import { jsPDF } from "jspdf";
import type { TripData } from "@/components/AddTripSheet";
import type { JourneyMilestone } from "@/hooks/useJourneyOverview";

export interface DischargePackInput {
  trip: TripData;
  milestones: JourneyMilestone[];
  totalDays: number | null;
  notes?: string[];
}

export interface DischargePackResult {
  blob: Blob;
  url: string;
  fileName: string;
}

/**
 * Build a printable Discharge Pack PDF summarising the completed journey.
 * English-only body (jsPDF default fonts do not include Arabic glyphs);
 * the in-app summary card carries the bilingual presentation.
 */
export function buildDischargePackPdf(input: DischargePackInput): DischargePackResult {
  const { trip, milestones, totalDays, notes = [] } = input;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = margin;

  const heading = (text: string, size = 14) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(size);
    doc.setTextColor(6, 16, 26);
    doc.text(text, margin, y);
    y += size + 6;
  };
  const body = (text: string, size = 11) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    doc.setTextColor(40, 50, 60);
    const lines = doc.splitTextToSize(text, pageWidth - margin * 2);
    lines.forEach((l: string) => {
      if (y > 780) { doc.addPage(); y = margin; }
      doc.text(l, margin, y);
      y += size + 4;
    });
  };
  const rule = () => {
    doc.setDrawColor(197, 150, 90);
    doc.setLineWidth(0.6);
    doc.line(margin, y, pageWidth - margin, y);
    y += 12;
  };

  // Title
  heading("Discharge Pack", 22);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated ${new Date().toLocaleString()}`, margin, y);
  y += 16;
  rule();

  // Trip overview
  heading("Trip Overview");
  body(`Destination: ${trip.destination || "—"}`);
  body(`Hospital: ${trip.hospital || "—"}`);
  body(`Specialty: ${trip.specialty || "—"}`);
  body(`Treating Doctor: ${trip.treatingDoctor || "—"}`);
  body(`Departure: ${trip.departureDate || "—"}`);
  body(`Return: ${trip.returnDate || "—"}`);
  if (totalDays != null) body(`Total Days: ${totalDays}`);
  if (trip.companion && trip.companionName) body(`Companion: ${trip.companionName}`);
  if (trip.insuranceRef) body(`Insurance Ref: ${trip.insuranceRef}`);
  y += 6;
  rule();

  // Milestones
  heading(`Milestones (${milestones.filter(m => m.state === "done").length}/${milestones.length} completed)`);
  milestones.forEach((m, idx) => {
    const status = m.state === "done" ? "✓" : m.state === "current" ? "•" : "○";
    body(`${status} ${idx + 1}. ${m.title}${m.date ? ` — ${m.date}` : ""}`);
  });
  y += 6;
  rule();

  // Notes
  if (notes.length) {
    heading("Key Notes");
    notes.forEach((n) => body(`• ${n}`));
    y += 6;
    rule();
  }

  // Footer disclaimer
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  const footer =
    "Generated by RufayQ for your personal records. Not a substitute for the official discharge summary issued by the treating facility.";
  const wrapped = doc.splitTextToSize(footer, pageWidth - margin * 2);
  if (y > 760) { doc.addPage(); y = margin; }
  doc.text(wrapped, margin, y);

  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  const safeDest = (trip.destination || "trip").replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  return { blob, url, fileName: `discharge-pack-${safeDest}.pdf` };
}
