project_id = "dlzwgkdiqabapgnvufil"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.scan-itinerary]
verify_jwt = false

[functions.push-dispatch-scheduled]
verify_jwt = false

[functions.lifestyle-buddy]
verify_jwt = false

[functions.chat-push]
verify_jwt = false

[functions.security-rescan]
verify_jwt = false
