project_id = "dlzwgkdiqabapgnvufil"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.scan-itinerary]
verify_jwt = false
