
REVOKE ALL ON FUNCTION public.admin_issue_refund(UUID, UUID, NUMERIC, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.credit_wallet(UUID, TEXT, NUMERIC, TEXT, TEXT, TEXT, UUID, UUID, TEXT, NUMERIC, NUMERIC, UUID, JSONB) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_or_create_wallet(UUID, TEXT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_issue_refund(UUID, UUID, NUMERIC, TEXT) TO authenticated;
